# Generated by Django 4.1.5 on 2023-01-05 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='posts')),
                ('caption', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('time_posted', models.DateTimeField()),
                ('hashtags', models.ManyToManyField(to='BackendApi.hashtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendApi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_liked', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendApi.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendApi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('follower_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_followed', models.DateTimeField()),
                ('follower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='BackendApi.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendApi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=255)),
                ('time_commented', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendApi.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendApi.user')),
            ],
        ),
    ]
